/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_sign_api */

#ifndef _Included_jni_sign_api
#define _Included_jni_sign_api
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_sign_api
 * Method:    SM2Sign
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1sign_1api_SM2Sign
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     jni_sign_api
 * Method:    SM2Verify
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jni_1sign_1api_SM2Verify
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jstring, jint);

/*
 * Class:     jni_sign_api
 * Method:    SM2SignP7
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1sign_1api_SM2SignP7
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jstring, jint);

/*
 * Class:     jni_sign_api
 * Method:    SM2VerifyP7
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jni_1sign_1api_SM2VerifyP7
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jni_sign_api
 * Method:    SM2CertGetPublicKey
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1sign_1api_SM2CertGetPublicKey
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jni_sign_api
 * Method:    SM3Hash
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1sign_1api_SM3Hash
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
